### ISSUE TITLE
There is no qiskit-aer 0.1.1 sdist tarball on pypi

### ISSUE THREAD

**Issue by mtreinish** [Qiskit/qiskit-aer#114]
### Informations

- **Qiskit Aer version**: 0.1.1
- **Python version**: 3.X
- **Operating system**: Any

### What is the current behavior?

The qiskit-aer 0.1.1 package on pypi is missing the sdist. This prevents installing it on any environment where there is no published wheel file. Which includes non-x86 arches and OS combinations not covered by the wheel files on: https://pypi.org/project/qiskit-aer/#files

### Steps to reproduce the problem

Try running `pip install qiskit-aer==0.1.1` on a system where there is no wheel file published.

### What is the expected behavior?

It will download the sdist and build aer for the system.

### Suggested solutions

Upload an sdist file for 0.1.1 (as was done in the 0.1.0 release).

**Comment by atilag** [comment]
Yep, there was no support for building Aer using pip until recently, we have merged a PR few days ago that would allow Aer to be built at installation time using an sdits package.

**Comment by junmendoza** [comment]
AFAIK this problem still occurs and i'm not sure why it is closed.
When installing: 
_pip install qiskit_
I get this error:
  _ERROR: Could not find a version that satisfies the requirement qiskit-aer==0.2.1 (from qiskit) (from versions: 0.1.0, 0.2.0)
ERROR: No matching distribution found for qiskit-aer==0.2.1 (from qiskit)_

When i tried installing aer separately:
_pip install qiskit-aer_
This only installs 0.2.0 (There is no 0.2.1)

I then just tried installing the latest version of qiskit:
_pip install qiskit==0.3.2_

And get this error:
_ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\unicorn\AppData\Local\Temp\pip-install-fw6tuaz_\matplotlib\_

I'm not sure what to make of this.
Can this be clarified?

**Comment by amiracam** [comment]
I'm trying to install qiskit on Python3.9 and I get the following:

C:\Users\Charles\PycharmProjects\Mastering-Quantum-Computing-with-IBM-QX>pip install --upgrade setuptools
Collecting setuptools
  Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed setuptools-50.3.2

C:\Users\Charles\PycharmProjects\Mastering-Quantum-Computing-with-IBM-QX>pip install qiskit
Collecting qiskit
  Downloading qiskit-0.23.0.tar.gz (4.1 kB)
Collecting qiskit-terra==0.16.0
  Downloading qiskit-terra-0.16.0.tar.gz (8.1 MB)
     |████████████████████████████████| 8.1 MB 3.3 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting qiskit-aer==0.7.0
  Downloading qiskit-aer-0.7.0.tar.gz (6.4 MB)
     |████████████████████████████████| 6.4 MB 6.4 MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\python3_9\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Charles\\AppData\\Local\\Temp\\pip-install-0vuod2m9\\qiskit-aer\\setup.py'"'"'; __file__='"'"'C:\\Users\\Charles\\AppData\\Local\\Temp\\pip-install-0vuod2m9\
\qiskit-aer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Charles\AppData\Local\Temp\pip-pip-egg-info-qt8
blg19'
         cwd: C:\Users\Charles\AppData\Local\Temp\pip-install-0vuod2m9\qiskit-aer\
    Complete output (322 lines):
    Collecting Cython>=0.27.1
      Using cached Cython-0.29.21-py2.py3-none-any.whl (974 kB)
    Installing collected packages: Cython
    Successfully installed Cython-0.29.21
    Collecting conan
      Downloading conan-1.30.2.tar.gz (623 kB)
    Collecting PyJWT<2.0.0,>=1.4.0
      Downloading PyJWT-1.7.1-py2.py3-none-any.whl (18 kB)
    Collecting requests<3.0.0,>=2.8.1
      Downloading requests-2.24.0-py2.py3-none-any.whl (61 kB)
    Collecting urllib3!=1.25.4,!=1.25.5
      Downloading urllib3-1.25.11-py2.py3-none-any.whl (127 kB)
    Collecting colorama<0.5.0,>=0.3.3
      Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)
    Collecting PyYAML<6.0,>=3.11
      Downloading PyYAML-5.3.1.tar.gz (269 kB)
    Collecting patch-ng<1.18,>=1.17.4
      Downloading patch-ng-1.17.4.tar.gz (17 kB)
    Collecting fasteners>=0.14.1
      Downloading fasteners-0.15-py2.py3-none-any.whl (23 kB)
    Requirement already satisfied: six<=1.15.0,>=1.10.0 in c:\users\charles\appdata\roaming\python\python39\site-packages (from conan) (1.15.0)
    Collecting node-semver==0.6.1
      Downloading node_semver-0.6.1-py3-none-any.whl (10 kB)
    Collecting distro<=1.5.0,>=1.0.2
      Downloading distro-1.5.0-py2.py3-none-any.whl (18 kB)
    Collecting future<0.19.0,>=0.16.0
      Using cached future-0.18.2.tar.gz (829 kB)
    Collecting pygments<3.0,>=2.0
      Downloading Pygments-2.7.1-py3-none-any.whl (944 kB)
    Collecting deprecation<2.1,>=2.0
      Downloading deprecation-2.0.7-py2.py3-none-any.whl (11 kB)
    Collecting tqdm<5,>=4.28.1
      Downloading tqdm-4.50.2-py2.py3-none-any.whl (70 kB)
    Collecting Jinja2<3,>=2.3
      Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
    Collecting python-dateutil<3,>=2.7.0
      Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
    Collecting bottle<0.13,>=0.12.8
      Downloading bottle-0.12.18-py3-none-any.whl (89 kB)
    Collecting pluginbase>=0.5
      Downloading pluginbase-1.0.0.tar.gz (41 kB)
    Collecting chardet<4,>=3.0.2
      Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
    Requirement already satisfied: certifi>=2017.4.17 in c:\users\charles\appdata\roaming\python\python39\site-packages (from requests<3.0.0,>=2.8.1->conan) (2020.6.20)
    Collecting idna<3,>=2.5
      Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
    Collecting monotonic>=0.1
      Downloading monotonic-1.5-py2.py3-none-any.whl (5.3 kB)
    Collecting packaging
      Using cached packaging-20.4-py2.py3-none-any.whl (37 kB)
    Collecting MarkupSafe>=0.23
      Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
    Collecting pyparsing>=2.0.2
      Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
    Using legacy 'setup.py install' for conan, since package 'wheel' is not installed.
    Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
    Using legacy 'setup.py install' for patch-ng, since package 'wheel' is not installed.
    Using legacy 'setup.py install' for future, since package 'wheel' is not installed.
    Using legacy 'setup.py install' for pluginbase, since package 'wheel' is not installed.
    Using legacy 'setup.py install' for MarkupSafe, since package 'wheel' is not installed.
    Installing collected packages: PyJWT, chardet, idna, urllib3, requests, colorama, PyYAML, patch-ng, monotonic, fasteners, node-semver, distro, future, pygments, pyparsing, packaging, deprecation, tqdm, MarkupSafe, Jinja2, python-dateutil, bottle, pluginbase, co
nan
        Running setup.py install for PyYAML: started
        Running setup.py install for PyYAML: finished with status 'done'
        Running setup.py install for patch-ng: started
        Running setup.py install for patch-ng: finished with status 'done'
        Running setup.py install for future: started
        Running setup.py install for future: finished with status 'done'
        Running setup.py install for MarkupSafe: started
        Running setup.py install for MarkupSafe: finished with status 'done'
        Running setup.py install for pluginbase: started
        Running setup.py install for pluginbase: finished with status 'done'
        Running setup.py install for conan: started
        Running setup.py install for conan: finished with status 'done'
    Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyJWT-1.7.1 PyYAML-5.3.1 bottle-0.12.18 chardet-3.0.4 colorama-0.4.4 conan-1.30.2 deprecation-2.0.7 distro-1.5.0 fasteners-0.15 future-0.18.2 idna-2.10 monotonic-1.5 node-semver-0.6.1 packaging-20.4 patch-ng
-1.17.4 pluginbase-1.0.0 pygments-2.7.1 pyparsing-2.4.7 python-dateutil-2.8.1 requests-2.24.0 tqdm-4.50.2 urllib3-1.25.11
    Collecting scikit-build
      Downloading scikit_build-0.11.1-py2.py3-none-any.whl (72 kB)
    Collecting wheel>=0.29.0
      Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
    Requirement already satisfied: packaging in c:\python3_9\lib\site-packages (from scikit-build) (20.4)
    Requirement already satisfied: distro in c:\python3_9\lib\site-packages (from scikit-build) (1.5.0)
    Requirement already satisfied: setuptools>=28.0.0; python_version >= "3" in c:\python3_9\lib\site-packages (from scikit-build) (50.3.2)
    Requirement already satisfied: pyparsing>=2.0.2 in c:\python3_9\lib\site-packages (from packaging->scikit-build) (2.4.7)
    Requirement already satisfied: six in c:\users\charles\appdata\roaming\python\python39\site-packages (from packaging->scikit-build) (1.15.0)
    Installing collected packages: wheel, scikit-build
    Successfully installed scikit-build-0.11.1 wheel-0.35.1
    Collecting pybind11>=2.4
      Downloading pybind11-2.6.0-py2.py3-none-any.whl (187 kB)
    Installing collected packages: pybind11
    Successfully installed pybind11-2.6.0
        ERROR: Command errored out with exit status 1:
         command: 'c:\python3_9\python.exe' 'c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Charles\AppData\Local\Temp\tmp1xu1jlsw'
             cwd: C:\Users\Charles\AppData\Local\Temp\pip-wheel-a67tk5bc\scipy
        Complete output (195 lines):
        setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\Charles\AppData\Local\Temp\pip-modern-metadata-qagb2bbz'), proceeding with generating Cython sources and expanding templates
          warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
        Running from SciPy source directory.
        lapack_opt_info:
        lapack_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE

        openblas_lapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE

        openblas_clapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas,lapack not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE

        flame_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries flame not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE

        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE

        atlas_3_10_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE

        atlas_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE

        atlas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE

        accelerate_info:
          NOT AVAILABLE

        lapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE

        C:\Users\Charles\AppData\Local\Temp\pip-build-env-yrg5j3zk\overlay\Lib\site-packages\numpy\distutils\system_info.py:1712: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          if getattr(self, '_calc_info_{}'.format(lapack))():
        lapack_src_info:
          NOT AVAILABLE

        C:\Users\Charles\AppData\Local\Temp\pip-build-env-yrg5j3zk\overlay\Lib\site-packages\numpy\distutils\system_info.py:1712: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          if getattr(self, '_calc_info_{}'.format(lapack))():
          NOT AVAILABLE

        Traceback (most recent call last):
          File "c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
            main()
          File "c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-yrg5j3zk\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-yrg5j3zk\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
            super(_BuildMetaLegacyBackend,
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-yrg5j3zk\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 583, in <module>
            setup_package()
          File "setup.py", line 579, in setup_package
            setup(**metadata)
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-yrg5j3zk\overlay\Lib\site-packages\numpy\distutils\core.py", line 137, in setup
            config = configuration()
          File "setup.py", line 477, in configuration
            raise NotFoundError(msg)
        numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
        ----------------------------------------
    ERROR: Command errored out with exit status 1: 'c:\python3_9\python.exe' 'c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Charles\AppData\Local\Temp\tmp1xu1jlsw' Check the logs for full command output
.
    Traceback (most recent call last):
      File "c:\python3_9\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\python3_9\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\python3_9\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Charles\\AppData\\Local\\Temp\\tmp8ah7qj_h', '--quiet', 'scipy>=1.0']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Charles\AppData\Local\Temp\pip-install-0vuod2m9\qiskit-aer\setup.py", line 78, in <module>
        setup(
      File "c:\python3_9\lib\site-packages\skbuild\setuptools_wrap.py", line 468, in setup
        return upstream_setup(*args, **kw)
      File "c:\python3_9\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\python3_9\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python3_9\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\python3_9\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\python3_9\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "c:\python3_9\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
        return installer(requirement)
      File "c:\python3_9\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\python3_9\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\python3_9\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Charles\\AppData\\Local\\Temp\\tmp8ah7qj_h', '--quiet', 'scipy>=1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

C:\Users\Charles\PycharmProjects\Mastering-Quantum-Computing-with-IBM-QX>pip install qiskit-aer
Collecting qiskit-aer
  Using cached qiskit-aer-0.7.0.tar.gz (6.4 MB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python3_9\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Charles\\AppData\\Local\\Temp\\pip-install-fextq4l2\\qiskit-aer\\setup.py'"'"'; __file__='"'"'C:\\Users\\Charles\\AppData\\Local\\Temp\\pip-install-fextq4l2\
\qiskit-aer\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Charles\AppData\Local\Temp\pip-pip-egg-info-wng
k40ld'
         cwd: C:\Users\Charles\AppData\Local\Temp\pip-install-fextq4l2\qiskit-aer\
    Complete output (233 lines):
        ERROR: Command errored out with exit status 1:
         command: 'c:\python3_9\python.exe' 'c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Charles\AppData\Local\Temp\tmp9rrllnro'
             cwd: C:\Users\Charles\AppData\Local\Temp\pip-wheel-yzrnuyt7\scipy
        Complete output (195 lines):
        setup.py:460: UserWarning: Unrecognized setuptools command ('dist_info --egg-base C:\Users\Charles\AppData\Local\Temp\pip-modern-metadata-1wlmayfb'), proceeding with generating Cython sources and expanding templates
          warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
        Running from SciPy source directory.
        lapack_opt_info:
        lapack_mkl_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries mkl_rt not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE
    
        openblas_lapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
        Could not locate executable ifort
        Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Could not locate executable DF
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
          NOT AVAILABLE
    
        openblas_clapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries openblas,lapack not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE
    
        flame_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries flame not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE
    
        atlas_3_10_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries tatlas,tatlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
          NOT AVAILABLE
    
        atlas_3_10_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries satlas,satlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_3_10_info'>
          NOT AVAILABLE
    
        atlas_threads_info:
        Setting PTATLAS=ATLAS
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries ptf77blas,ptcblas,atlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_threads_info'>
          NOT AVAILABLE
    
        atlas_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in c:\python3_9\lib
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in C:\
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack_atlas not found in c:\python3_9\libs
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries f77blas,cblas,atlas not found in c:\python3_9\libs
        <class 'numpy.distutils.system_info.atlas_info'>
          NOT AVAILABLE
    
        accelerate_info:
          NOT AVAILABLE
    
        lapack_info:
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
          libraries lapack not found in ['c:\\python3_9\\lib', 'C:\\', 'c:\\python3_9\\libs']
          NOT AVAILABLE
    
        C:\Users\Charles\AppData\Local\Temp\pip-build-env-1n8quyqi\overlay\Lib\site-packages\numpy\distutils\system_info.py:1712: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          if getattr(self, '_calc_info_{}'.format(lapack))():
        lapack_src_info:
          NOT AVAILABLE
    
        C:\Users\Charles\AppData\Local\Temp\pip-build-env-1n8quyqi\overlay\Lib\site-packages\numpy\distutils\system_info.py:1712: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          if getattr(self, '_calc_info_{}'.format(lapack))():
          NOT AVAILABLE
    
        Traceback (most recent call last):
          File "c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
            main()
          File "c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-1n8quyqi\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-1n8quyqi\overlay\Lib\site-packages\setuptools\build_meta.py", line 253, in run_setup
            super(_BuildMetaLegacyBackend,
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-1n8quyqi\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 583, in <module>
            setup_package()
          File "setup.py", line 579, in setup_package
            setup(**metadata)
          File "C:\Users\Charles\AppData\Local\Temp\pip-build-env-1n8quyqi\overlay\Lib\site-packages\numpy\distutils\core.py", line 137, in setup
            config = configuration()
          File "setup.py", line 477, in configuration
            raise NotFoundError(msg)
        numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
        ----------------------------------------
    ERROR: Command errored out with exit status 1: 'c:\python3_9\python.exe' 'c:\python3_9\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\Charles\AppData\Local\Temp\tmp9rrllnro' Check the logs for full command output
.
    Traceback (most recent call last):
      File "c:\python3_9\lib\site-packages\setuptools\installer.py", line 126, in fetch_build_egg
        subprocess.check_call(cmd)
      File "c:\python3_9\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['c:\\python3_9\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Charles\\AppData\\Local\\Temp\\tmpzwcojt8f', '--quiet', 'scipy>=1.0']' returned non-zero exit status 1.
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Charles\AppData\Local\Temp\pip-install-fextq4l2\qiskit-aer\setup.py", line 78, in <module>
        setup(
      File "c:\python3_9\lib\site-packages\skbuild\setuptools_wrap.py", line 468, in setup
        return upstream_setup(*args, **kw)
      File "c:\python3_9\lib\site-packages\setuptools\__init__.py", line 152, in setup
        _install_setup_requires(attrs)
      File "c:\python3_9\lib\site-packages\setuptools\__init__.py", line 147, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python3_9\lib\site-packages\setuptools\dist.py", line 673, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\python3_9\lib\site-packages\pkg_resources\__init__.py", line 764, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\python3_9\lib\site-packages\pkg_resources\__init__.py", line 1049, in best_match
        return self.obtain(req, installer)
      File "c:\python3_9\lib\site-packages\pkg_resources\__init__.py", line 1061, in obtain
        return installer(requirement)
      File "c:\python3_9\lib\site-packages\setuptools\dist.py", line 732, in fetch_build_egg
        return fetch_build_egg(self, req)
      File "c:\python3_9\lib\site-packages\setuptools\installer.py", line 128, in fetch_build_egg
        raise DistutilsError(str(e)) from e
    distutils.errors.DistutilsError: Command '['c:\\python3_9\\python.exe', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', 'C:\\Users\\Charles\\AppData\\Local\\Temp\\tmpzwcojt8f', '--quiet', 'scipy>=1.0']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mtreinish** [comment]
@amiracam the issue you pasted is unrelated to this. It actually isn't a qiskit-aer issue at all. What it is failing in that log output is building numpy and scipy for python 3.9 in your environment. Python 3.9 was only very recently released and nothing really supports it yet, and it will be some more time before everything does. You can go about trying to install all of aer's python dependencies from source and then build aer from source, but it will be a large effort (especially on windows). It would be easier to just downgrade to Python 3.8 and until qiskit supports python 3.9 (which can't happen until all its dependencies support 3.9). 

Feel free to open a new issue about this, but I've been tracking adding python 3.9 support independently already. I was going to open a PR for it once numpy and scipy have 3.9 support released (although it will likely be stuck on other dependencies after that).
