### ISSUE TITLE
Aer job uses too much memory on a hpc and is killed by scheduler

### ISSUE THREAD

**Issue by chris-n-self** [Qiskit/qiskit-aer#661]
### Informations

- **Qiskit Aer version**: 0.3.4
- **Python version**: 3.7.5
- **Operating system**: CentOS 7.7.1908

### What is the current behavior?

I am running simulations on a hpc cluster and about half the time the memory usage spikes and the job is killed by the scheduler. The simulations I'm doing are very small (4 qubits), however the number of circuits submitted to `execute`  is large (~1000). I am using a `qasm_simulator` backend and handling circuit execution with aqua's `QuantumInstance` class. Additionally, I have set the backend option `max_memory_mb` to be within the memory requested from the scheduler. From looking through the code I have not been able to find any other options that set memory limits. Normal executions of the job (ones that complete) have a max memory usage of about 3GB, and the ones that experience a memory spike and are killed go up to about ~20GB (in this case I had requested 4GB RAM from the scheduler). Requesting large amounts of memory from the scheduler causes my jobs to queue for a long time, so although a simple fix would be to request more memory it is not ideal. 

### Steps to reproduce the problem

I have tried to reproduce the issue, but on many repeated runs (on a machine with large amounts of memory available) I have not seen instances that have high memory usage higher than ~2-3GB. 

### What is the expected behavior?

I would like to be able to set the amount of memory used by the QASM simulator in my code.

**Comment by chriseclectic** [comment]
@chris-n-self Can you give an example of the Aqua code that was causing memory leak to help debug?

**Comment by atilag** [comment]
Hey @chris-n-self thanks for reporting this. I'd like to take a look at this... could you provide an example so we can reproduce this error? Thanks!

**Comment by chriseclectic** [comment]
I think this should have been fixed in #763

**Comment by chris-n-self** [comment]
Sorry for not responding sooner to the previous messages! I have updated to Aer 0.5.2 (which I think includes fix #763) but I still get this issue. Here is a small example that reliably gives me the error:

```python
qsub_opts = {
    'scheduler':'pbs',
    'hours':12,
    'num_procs':1,
    'gigabytes':1,
}
backend_options = {
    'max_parallel_threads':qsub_opts['num_procs'],
    'max_parallel_experiments':qsub_opts['num_procs'],
    'max_memory_mb':qsub_opts['gigabytes']*1024,
}

def run(num_measurements,backend_options=None,**kwargs):
    """
    """
    from qiskit import QuantumCircuit,Aer
    from qiskit.quantum_info import random_unitary
    from qiskit.aqua import QuantumInstance

    # make circuits with random measurements
    circs = []
    for n in range(num_measurements):
        rand_measurement = QuantumCircuit(4)
        for i in range(4):
            R = random_unitary(2)
            rand_measurement.append(R,[i])
        rand_measurement.measure_all()
        rand_measurement.name = 'circ'+f'{n}'
        circs.append(rand_measurement)
        
    # run on QuantumInstance
    shots = 1024
    quantum_instance = QuantumInstance(Aer.get_backend('qasm_simulator'),
                                       shots=shots,
                                       backend_options=backend_options)
    t_rand_measurement = quantum_instance.transpile(circs)
    results = quantum_instance.execute(t_rand_measurement,had_transpiled=True)
    
    tot_mean = 0.
    for n in range(num_measurements):
        mean = 0.
        for k,v in results.get_counts('circ'+f'{n}').items():
            mean += int(k,base=2)*v/shots
        tot_mean += mean/num_measurements
    
    return tot_mean

run(10000,backend_options=backend_options)
```

I ran this 100 times on the cluster I am using and 71 of the jobs went over the 1GB memory allowance. Looking through the job reports it seems that most of them were using 3GB when they were killed by the scheduler.

```
============================================

        Job resource usage summary 

                 Memory (GB)    NCPUs
 Requested  :         1             1
 Used       :         3 (peak)   0.44 (ave)

============================================
```

**Comment by rumschuettel** [comment]
I can confirm this. It looks like `execute(experiment, ...)` for a long list of experiment parallelizes over them, regardless of any settings of the simulator (in particular it seems to ignore `max_parallel_experiments=1`).

This is pretty much a showstopper tbh, since if you run anything on a large shared node where you only have a fraction of CPUs and memory, but qiskit spawns like 20 times as many threads as you have cores reserved, you *will* run out of memory.

**Comment by chriseclectic** [comment]
Closing this issue as stale. Feel free to reopen after 0.9 release if there are still issues with this.

Note that execute is deprecated and you should separately transpile your circuits and then run them using `backend.run`. If transpile is causing the issue this would indicate an issue with terra transpiler or retworkx library. If the `run` command is causing the additional threads then we this issue should be revisited here.
